query {
  token(id: "0xa7d7079b0fead91f3e65f86e8915cb59c1a4c664") {
    symbol
    decimals
    totalSupply
    derivedAVAX
  }

  bundle(id: 1) {
    avaxPrice
  }
  pairs(where:{name:"USDC.e-WAVAX"}) {
    name
    reserve0
    reserve1
    token0Price
    token1Price
  }
}
